# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'API_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API_Project
  pod 'Alamofire', '~> 5.2' 
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
end
