# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NAVER_Map' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'NMapsMap'
  # Pods for NAVER_Map

  target 'NAVER_MapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NAVER_MapUITests' do
    # Pods for testing
  end

end
